name:                better-learn
version:             0.1.0.0
github:              "githubuser/better-learn"
license:             BSD3
author:              "Petter Egesund"
maintainer:          "petter.egesund@gmail.com"
copyright:           "2018 Petter Egesund"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/better-learn#readme>

dependencies:
- base >= 4.7 && < 5
- containers 
- time
- binary
- QuickCheck

library:
  source-dirs: src

executables:
  better-learn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - better-learn

tests:
  better-learn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - better-learn
